# See: https://aka.ms/yaml

trigger:
  - main

stages:
  - stage: Quality_Control
    displayName: Quality Control
    jobs:

      # Run the linters once on the latest version of linux. If this
      # fails, stop the pipeline before running heavy
      # platform-specific unit tests and builds.
      - job: lint
        displayName: Lint
        pool:
          vmImage: "ubuntu-latest"
        steps:
          - task: UsePythonVersion@0
            displayName: "Use Python version"
            inputs:
              versionSpec: "3.10"
              architecture: "x64"

          - script: python -m pip install -r requirements-dev.txt
            displayName: "CR-QC: Install local package"

          - script: cr --help
            displayName: "CR-QC: Run CLI"

          - script: flake8 .
            displayName: "CR-QC: flake8"

          - script: mypy .
            displayName: "CR-QC: mypy"

          - script: black --check .
            displayName: "CR-QC: black"


  # Run tests and build bundles for each platform.
  - stage: Build_Dist
    displayName: Build Distributables
    dependsOn: Quality_Control
    condition: succeeded('Quality_Control')
    jobs:
      - job: windows10
        displayName: Windows 10
        pool:
          vmImage: "windows-2019"
        steps:
          - task: UsePythonVersion@0
            displayName: "Use Python version"
            inputs:
              versionSpec: "3.10"
              architecture: "x64"

          - script: python -m pip install -r requirements-pipeline.txt
            displayName: "CR-QC: Install"

          - script: pytest
            displayName: "CR-QC: Test"

          - script: pyinstaller --clean --dist ./tmp/ ./cr.spec
            displayName: "CR-BLD: Build"

          - pwsh: New-Item -Type Directory -Force ./dist/; Move-Item ./tmp/cr.exe ./dist/
            displayName: "CR-BLD: Copy"

          - publish: $(System.DefaultWorkingDirectory)\dist\
            artifact: dist

      - job: macos11
        displayName: macOS 11
        pool:
          vmImage: "macOS-11"

        steps:
          - task: UsePythonVersion@0
            displayName: "Use Python version"
            inputs:
              versionSpec: "3.10"
              architecture: "x64"

          - script: python -m pip install -r requirements-pipeline.txt
            displayName: "CR-QC: Install"

          - script: pytest
            displayName: "CR-QC: Test"

          - script: pyinstaller --clean --dist ./tmp/ ./cr.spec
            displayName: "CR-BLD: Build"

          - script: mkdir -p ./dist/; mv ./tmp/cr ./dist/cr-macos
            displayName: "CR-BLD: Copy"

          - publish: $(System.DefaultWorkingDirectory)/dist/
            artifact: dist

      - job: ubuntu2004
        displayName: Ubuntu 20.04
        pool:
          vmImage: "ubuntu-20.04"

        steps:
          - task: UsePythonVersion@0
            displayName: "Use Python version"
            inputs:
              versionSpec: "3.10"
              architecture: "x64"

          - script: python -m pip install -r requirements-pipeline.txt
            displayName: "CR-QC: Install"

          - script: pytest
            displayName: "CR-QC: Test"

          - script: pyinstaller --clean --dist ./tmp/ ./cr.spec
            displayName: "CR-BLD: Build"

          - script: mkdir -p ./dist/; mv ./tmp/cr ./dist/cr-linux
            displayName: "CR-BLD: Copy"

          - script: python -m build --outdir ./dist/
            displayName: "CR-BLD: PyPI"

          - publish: $(System.DefaultWorkingDirectory)/dist/
            artifact: dist
